import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useLocation } from 'react-router-dom';
import { useSupabase } from '../../culinary/components/SupabaseProvider';
import { fetchCookbook } from '../../culinary/modules/cookbookSupabase';
import { RecipeCard } from './ProcessMatcherModal';
import jsPDF from 'jspdf';
import { groupIngredientsByMarketType, getEstimatedPrice } from '../utils/ingredientMapping';

interface BuildMenuModalProps {
  open: boolean;
  onClose: () => void;
  onFindMarkets: (selectedRecipes: RecipeCard[]) => void;
}

const BuildMenuModal: React.FC<BuildMenuModalProps> = ({ open, onClose, onFindMarkets }) => {
  const { t } = useTranslation();
  const location = useLocation();
  const discipline = location.pathname.split('/').filter(Boolean)[0] || 'culinary';
  const bt = (key: string) => t(`buildMenu.disciplineCopy.${discipline}.${key}`, { defaultValue: t(`buildMenu.${key}`) });
  const { user } = useSupabase();
  const [recipes, setRecipes] = useState<RecipeCard[]>([]);
  const [selectedRecipeIds, setSelectedRecipeIds] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (open && user?.id) {
      loadRecipes();
    }
  }, [open, user?.id]);

  const loadRecipes = async () => {
    if (!user?.id) return;
    
    try {
      setLoading(true);
      const savedRecipes = await fetchCookbook(user.id);
      setRecipes(savedRecipes || []);
    } catch (err) {
      console.error('Error loading cookbook recipes:', err);
      setRecipes([]);
    } finally {
      setLoading(false);
    }
  };

  const toggleRecipe = (recipeId: string) => {
    const newSelected = new Set(selectedRecipeIds);
    if (newSelected.has(recipeId)) {
      newSelected.delete(recipeId);
    } else {
      newSelected.add(recipeId);
    }
    setSelectedRecipeIds(newSelected);
  };

  const handleFindMarkets = () => {
    const selected = recipes.filter(r => selectedRecipeIds.has(r.id));
    onFindMarkets(selected);
  };

  const handleCreateMenuPDF = () => {
    const selected = recipes.filter(r => selectedRecipeIds.has(r.id));
    if (selected.length === 0) return;

    const pdf = new jsPDF();
    let yPos = 20;

    // Title
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.text(bt('myMenu'), 105, yPos, { align: 'center' });
    yPos += 15;

    // Menu Items
    pdf.setFontSize(14);
    pdf.text(bt('selectedRecipes'), 20, yPos);
    yPos += 8;
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    selected.forEach((recipe, idx) => {
      pdf.text(`${idx + 1}. ${recipe.title}`, 25, yPos);
      yPos += 6;
    });
    yPos += 5;

    // Extract and deduplicate ingredients
    const allIngredients: string[] = [];
    selected.forEach(recipe => {
      if (recipe.ingredients && Array.isArray(recipe.ingredients)) {
        allIngredients.push(...recipe.ingredients);
      }
    });
    const uniqueIngredients = Array.from(
      new Set(allIngredients.map(ing => ing.toLowerCase()))
    ).map(ing => allIngredients.find(original => original.toLowerCase() === ing) || ing);
    const ingredientsByType = groupIngredientsByMarketType(uniqueIngredients);

    // Shopping List by Market Type
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('SHOPPING LIST', 20, yPos);
    yPos += 8;

    const marketTypeLabels: Record<string, string> = {
      seafood: '🐟 Seafood Markets',
      butcher: '🥩 Butcher',
      produce: '🥦 Produce',
      dairy: '🥛 Dairy',
      grocery: '🛒 Grocery',
      deli: '🥪 Deli/Bakery',
      farms: '🚜 Farms'
    };

    Object.entries(ingredientsByType).forEach(([type, ingredients]) => {
      if (ingredients.length === 0) return;
      
      // Check if we need a new page
      if (yPos > 250) {
        pdf.addPage();
        yPos = 20;
      }

      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text(marketTypeLabels[type] || type, 20, yPos);
      yPos += 6;

      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      let subtotal = 0;
      ingredients.forEach(ing => {
        const priceInfo = getEstimatedPrice(ing);
        const priceText = priceInfo ? ` ~$${priceInfo.price}/${priceInfo.unit}` : '';
        pdf.text(`• ${ing}${priceText}`, 25, yPos);
        if (priceInfo) subtotal += priceInfo.price;
        yPos += 5;
      });

      if (subtotal > 0) {
        pdf.setFont('helvetica', 'italic');
        pdf.text(`Estimated subtotal: ~$${subtotal.toFixed(2)}`, 25, yPos);
        yPos += 7;
      }
      yPos += 3;
    });

    // Footer
    if (yPos > 250) {
      pdf.addPage();
      yPos = 20;
    }
    yPos += 10;
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'italic');
    pdf.text('Generated by PorkChop Ed Tech', 105, yPos, { align: 'center' });
    pdf.text('Prices are estimates only', 105, yPos + 5, { align: 'center' });

    // Download
    pdf.save('my-menu.pdf');
  };

  if (!open) return null;

  return (
    <div className="fixed inset-0 overflow-y-auto bg-black bg-opacity-50 flex items-center justify-center z-50 p-4" onClick={onClose}>
      <div className="bg-white rounded-lg shadow-xl border-4 border-maineBlue max-w-4xl w-full max-h-[85vh] flex flex-col" onClick={e => e.stopPropagation()}>
        <div className="p-6 flex-1 overflow-hidden flex flex-col">
          {/* Header */}
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-2xl font-bold text-maineBlue font-retro">📋 Build Production Plan</h2>
            <button 
              onClick={onClose}
              className="text-gray-500 hover:text-gray-700 text-2xl"
            >
              ×
            </button>
          </div>

          {/* Instructions */}
          <p className="text-sm text-gray-600 mb-4">
            {bt('selectRecipes')}
          </p>

          {/* Two Column Layout */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4 flex-1 overflow-hidden">
            {/* Left: Recipe Picklist */}
            <div className="flex flex-col overflow-hidden">
              <h3 className="text-sm font-semibold text-gray-700 mb-2">📋 {bt('availableItems')}</h3>
              {loading ? (
                <div className="text-center py-8">
                  <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-maineBlue mx-auto"></div>
                  <p className="text-gray-500 mt-2">{bt('loading')}</p>
                </div>
              ) : recipes.length === 0 ? (
                <div className="text-center py-8">
                  <p className="text-gray-500 text-sm">{bt('noItems')}</p>
                </div>
              ) : (
                <div className="space-y-2 overflow-y-auto pr-2" style={{maxHeight: '280px'}}>
                  {recipes.map((recipe) => (
                    <label
                      key={recipe.id}
                      className={`flex items-center p-2 rounded-lg border cursor-pointer transition-colors ${
                        selectedRecipeIds.has(recipe.id)
                          ? 'border-maineBlue bg-blue-50'
                          : 'border-gray-200 hover:border-gray-300'
                      }`}
                    >
                      <input
                        type="checkbox"
                        checked={selectedRecipeIds.has(recipe.id)}
                        onChange={() => toggleRecipe(recipe.id)}
                        className="mr-2 h-4 w-4 text-maineBlue"
                      />
                      <div className="flex-1 min-w-0">
                        <div className="font-medium text-sm text-gray-900 truncate">{recipe.title}</div>
                        {recipe.ingredients && (
                          <div className="text-xs text-gray-400">
                            {bt('itemsCount').replace('{count}', recipe.ingredients.length.toString())}
                          </div>
                        )}
                      </div>
                    </label>
                  ))}
                </div>
              )}
            </div>

            {/* Right: Your Production Plan */}
            <div className="flex flex-col overflow-hidden">
              <h3 className="text-sm font-semibold text-gray-700 mb-2">📋 {bt('yourMenu')}</h3>
              {selectedRecipeIds.size === 0 ? (
                <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center">
                  <p className="text-gray-400 text-sm">{bt('selectToStart')}</p>
                </div>
              ) : (
                <div className="space-y-2 overflow-y-auto pr-2" style={{maxHeight: '280px'}}>
                  {recipes
                    .filter(r => selectedRecipeIds.has(r.id))
                    .map((recipe, idx) => (
                      <div
                        key={recipe.id}
                        className="p-3 bg-sand rounded-lg border border-maineBlue"
                      >
                        <div className="flex items-start justify-between">
                          <div className="flex-1">
                            <div className="font-medium text-gray-900">{idx + 1}. {recipe.title}</div>
                            {recipe.ingredients && (
                              <div className="text-xs text-gray-500 mt-1">
                                {bt('itemsCountNeeded').replace('{count}', recipe.ingredients.length.toString())}
                              </div>
                            )}
                          </div>
                          <button
                            onClick={() => toggleRecipe(recipe.id)}
                            className="text-red-500 hover:text-red-700 ml-2"
                            title={bt('removeFromMenu')}
                          >
                            ✕
                          </button>
                        </div>
                      </div>
                    ))}
                </div>
              )}
            </div>
          </div>

          {/* Footer */}
          <div className="flex items-center justify-between pt-4 border-t flex-shrink-0">
            <div className="text-sm text-gray-600">
              {selectedRecipeIds.size} {bt('recipesSelected')}
            </div>
            <div className="flex gap-2">
              <button
                onClick={onClose}
                className="px-4 py-2 text-gray-600 hover:text-gray-800 font-medium"
              >
                {bt('cancel')}
              </button>
              <button
                onClick={handleCreateMenuPDF}
                disabled={selectedRecipeIds.size === 0}
                className={`px-4 py-2 rounded font-bold transition-colors ${
                  selectedRecipeIds.size === 0
                    ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                    : 'bg-seafoam text-maineBlue hover:bg-maineBlue hover:text-seafoam border border-maineBlue'
                }`}
              >
                📄 Create Plan (PDF)
              </button>
              <button
                onClick={handleFindMarkets}
                className="px-6 py-2 rounded font-bold transition-colors bg-red-600 text-white hover:bg-red-700 border border-red-600"
              >
                🏭 Find Suppliers
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BuildMenuModal;
